// <auto-generated />
using ConsoleApp.SQLite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ConsoleApp.SQLite.Migrations
{
    [DbContext(typeof(ReefSurvey))]
    partial class ReefSurveyModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("ConsoleApp.SQLite.FishInfo", b =>
                {
                    b.Property<int>("FishInfoID")
                        .ValueGeneratedOnAdd();

                    b.Property<float>("FishLength");

                    b.Property<int>("MetricID");

                    b.Property<string>("StructureType");

                    b.HasKey("FishInfoID");

                    b.ToTable("FishInfos");
                });

            modelBuilder.Entity("ConsoleApp.SQLite.FishName", b =>
                {
                    b.Property<int>("FishNameID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CommonName");

                    b.Property<string>("ScientificName");

                    b.HasKey("FishNameID");

                    b.ToTable("FishNames");
                });

            modelBuilder.Entity("ConsoleApp.SQLite.FishObserved", b =>
                {
                    b.Property<int>("FishObservedID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Family");

                    b.Property<int>("LocationID");

                    b.Property<int>("MetricID");

                    b.Property<string>("Trophic");

                    b.HasKey("FishObservedID");

                    b.ToTable("FishObserveds");
                });

            modelBuilder.Entity("ConsoleApp.SQLite.Location", b =>
                {
                    b.Property<int>("LocationID")
                        .ValueGeneratedOnAdd();

                    b.Property<float>("Latitude");

                    b.Property<float>("Longitude");

                    b.Property<int>("RegionID");

                    b.HasKey("LocationID");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("ConsoleApp.SQLite.Region", b =>
                {
                    b.Property<int>("RegionID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("RegionName");

                    b.Property<string>("SubRegionName");

                    b.HasKey("RegionID");

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("ConsoleApp.SQLite.Survey", b =>
                {
                    b.Property<int>("SurveyID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BatchCode");

                    b.Property<int>("FishCount");

                    b.Property<string>("Management");

                    b.Property<int>("ObservationID");

                    b.Property<string>("StudyArea");

                    b.Property<string>("SurveyDate");

                    b.Property<int>("SurveyIndex");

                    b.Property<string>("SurveyYear");

                    b.HasKey("SurveyID");

                    b.ToTable("Surveys");
                });
#pragma warning restore 612, 618
        }
    }
}
